# Generated by Django 3.1.1 on 2020-09-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
