# Generated by Django 3.1.1 on 2020-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('S', 'Submitted')], default='O', max_length=2),
        ),
    ]
