# Generated by Django 3.1.1 on 2020-09-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200915_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='basket',
            new_name='cart',
        ),
    ]
